#!/usr/bin/python

import json, os, sys

class Concatenator:
	def __init__(self):
		self.config_file = "prod.json"
		if (len(sys.argv) > 1)  and (sys.argv[1] == "init"):
			self.write_config_file()
			exit(0)
		self.contents = []
		self.read_config()
		self.get_contents()
		return

	# read the configuration file 
	# to get the appropriate files and output
	def read_config(self):
		try:
			self.config = json.loads(open(self.config_file, 'r').read())
		except Exception as e:
			print "Could not read config file: %s" % e
			exit(1)
		return

	def get_contents(self):
		for i in range(0, len(self.config)):
			for f in self.config[i]['files']:
				try:
					self.contents.append(open(self.config[i]['base'] + f).read())
				except Exception as e:
					print "Error: %s" % e
			self.join_content()
			self.write_content(i)
		return

	def join_content(self):
		self.concat = "\n".join(self.contents)
		self.contents = []
		return

	def write_content(self, index):
		try:
			open(self.config[index]['base'] + self.config[index]['output'], "w").write(self.concat)
			self.concat = ""
		except Exception as e:
			print "Error: %s" % e
		return

	def write_config_file(self):
		self.config_content = """{
	"base": "./_js/",
	"output": "compressed/main.cat.js",
	"files": [
		"libs/jquery/jquery-min.js",
		"main.js"
	]
}"""
		open(self.config_file,'w').write(self.config_content)


if __name__ == '__main__':
	c = Concatenator()
